### ISSUE TITLE
glasp_yt_summary_btn_on_img covers youtube "watch later" button

### ISSUE THREAD

**Issue by adotland** [kazuki-sf/YouTube_Summary_with_ChatGPT#4]
Those of us who prefer to disable "inline playback" and use the old style "watch later" buttons are not able to use those buttons with this extension installed. Please consider moving the button to the left corner instead and/or giving user the option to disable the button. Thanks.

![Screenshot 2023-01-17 124400](https://user-images.githubusercontent.com/1982042/213010083-2faba288-fa93-4273-b94b-e10bf337515a.jpg)

**Comment by kazuki-sf** [comment]
Hi @adotland,
Thanks for the feedback!
I'll figure out the better way for all :)
At the same time, if you don't like it, please download this open-source file and upload it via your developer mode on your browser :)
I didn't reflect this update in the open-sourced code.
Thanks,
Kazuki
