### ISSUE TITLE
clicking the send button does not work

### ISSUE THREAD

**Issue by ThomasNL1995** [kazuki-sf/YouTube_Summary_with_ChatGPT#8]
In the index.js code, you are calling .click() on the send button, but the disabled attribute is still on the button so nothing happens.

I suggest you add a line where you remove the disabled attribute on the button before you click it.

**Comment by kazuki-sf** [comment]
Thanks!

Actually, it's fixed in the production :)
https://chrome.google.com/webstore/detail/youtube-summary-with-chat/nmmicjeknamkfloonkhhcjmomieiodli
